package com.stu.Model;
// Generated Apr 27, 2023, 6:03:44 AM by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Lop generated by hbm2java
 */
@Entity
@Table(name = "lop", catalog = "qlsv")
public class Lop implements java.io.Serializable {
	@Expose
	private int malop;
	@Expose
	private String tenlop;
	@Expose(serialize = false)
	private Set<Sinhvien> sinhviens = new HashSet<Sinhvien>(0);

	public Lop() {
	}

	public Lop(int malop) {
		this.malop = malop;
	}

	public Lop(int malop, String tenlop, Set<Sinhvien> sinhviens) {
		this.malop = malop;
		this.tenlop = tenlop;
		this.sinhviens = sinhviens;
	}

	@Id
	@Column(name = "malop", unique = true, nullable = false)
	@GeneratedValue(strategy = IDENTITY)
	public int getMalop() {
		return this.malop;
	}

	public void setMalop(int malop) {
		this.malop = malop;
	}

	@Override
	public String toString() {
		return "Lop [malop=" + malop + ", tenlop=" + tenlop + ", sinhviens=" + sinhviens + "]";
	}

	@Column(name = "tenlop", length = 50)
	public String getTenlop() {
		return this.tenlop;
	}

	public void setTenlop(String tenlop) {
		this.tenlop = tenlop;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "lop")
	public Set<Sinhvien> getSinhviens() {
		return this.sinhviens;
	}

	public void setSinhviens(Set<Sinhvien> sinhviens) {
		this.sinhviens = sinhviens;
	}

}
